engines:
  fixme:
    enabled: true
  checkstyle:
    enabled: true
    checks:
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck:
        enabled: false
ratings:
  paths:
  - "**.java"
exclude_paths: []